// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -package=wallet -destination=service_mock.go Service
//

// Package wallet is a generated GoMock package.
package wallet

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddOperation mocks base method.
func (m *MockService) AddOperation(userID int64, opt Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOperation", userID, opt)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOperation indicates an expected call of AddOperation.
func (mr *MockServiceMockRecorder) AddOperation(userID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOperation", reflect.TypeOf((*MockService)(nil).AddOperation), userID, opt)
}

// Save mocks base method.
func (m *MockService) Save(wo Wallet) (Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", wo)
	ret0, _ := ret[0].(Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockServiceMockRecorder) Save(wo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockService)(nil).Save), wo)
}

// ShowWallet mocks base method.
func (m *MockService) ShowWallet(id int64) (Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowWallet", id)
	ret0, _ := ret[0].(Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowWallet indicates an expected call of ShowWallet.
func (mr *MockServiceMockRecorder) ShowWallet(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowWallet", reflect.TypeOf((*MockService)(nil).ShowWallet), id)
}
